"""Initial migration 2

Revision ID: 9b59cd671637
Revises: 96d75bf8beba
Create Date: 2024-08-05 12:13:31.822682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b59cd671637'
down_revision = '96d75bf8beba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index('slug')
        batch_op.drop_column('slug')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index('slug')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.create_index('slug', ['slug'], unique=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.create_index('slug', ['slug'], unique=True)

    # ### end Alembic commands ###
