"""Update migrate v3

Revision ID: 9fe884da428b
Revises: c8fce3c19933
Create Date: 2024-05-29 02:45:13.891457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe884da428b'
down_revision = 'c8fce3c19933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
