"""Initial migration

Revision ID: ed164a4ef675
Revises: c6ebb19e3bc2
Create Date: 2024-05-31 12:08:24.576893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed164a4ef675'
down_revision = 'c6ebb19e3bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_index('ix_grant_code')

    op.drop_table('grant')
    op.drop_table('token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=40), nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expires', sa.DATETIME(), nullable=True),
    sa.Column('_scopes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('grant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('code', sa.VARCHAR(length=255), nullable=False),
    sa.Column('redirect_uri', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expires', sa.DATETIME(), nullable=True),
    sa.Column('_scopes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.create_index('ix_grant_code', ['code'], unique=False)

    op.create_table('client',
    sa.Column('name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('description', sa.VARCHAR(length=400), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('client_secret', sa.VARCHAR(length=55), nullable=False),
    sa.Column('confidential', sa.BOOLEAN(), nullable=True),
    sa.Column('_redirect_uris', sa.TEXT(), nullable=True),
    sa.Column('_default_scopes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_secret'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
